name: Commit Issue Commenter

on: issues

jobs:
  checkIssue:
    name: Comment From New Issue
    runs-on: ubuntu-latest
    steps:
      - uses: explooosion/winnie-greet-actions@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
